### ISSUE TITLE
Math.pow is not supported.

### ISSUE THREAD

**Issue by MareoRaft** [yerich/Graphr#6]
I cannot use `pow()` or `Math.pow()` to create my equations.  This forces me to rewrite the same thing multiple times and multiply it together.  This is an issue especially when I'm tinkering around with a constant and I need to change it in three places every time.

Thanks for the cool website though.  Looks good.

**Comment by yerich** [comment]
Thanks for using the tool!

Powers are supported through the ^ operator,  e.g. y=x^(x - 2).
